#
# Makefile fragment for Linux 2.6
# Broadcom BCMSDH Driver
#
# $ Copyright Open Broadcom Corporation $
#
#
# <<Broadcom-WL-IPTag/Open:>>
#
# $Id: makefile.26,v 1.4 2008-05-07 00:22:16 $

obj-m += bcmsdh_driver.o
bcmsdh_driver-objs = $(BCMSDHOFILES)
EXTRA_CFLAGS = $(BCMSDHCFLAGS)
